/*
 * Test application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/NewNode', 'model/Node'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/NewNode'), require('../model/Node'));
  } else {
    // Browser globals (root is window)
    if (!root.TestApplicationApi) {
      root.TestApplicationApi = {};
    }
    root.TestApplicationApi.NodesApi = factory(root.TestApplicationApi.ApiClient, root.TestApplicationApi.Error, root.TestApplicationApi.NewNode, root.TestApplicationApi.Node);
  }
}(this, function(ApiClient, Error, NewNode, Node) {
  'use strict';

  /**
   * Nodes service.
   * @module api/NodesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new NodesApi. 
   * @alias module:api/NodesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getNodes operation.
     * @callback module:api/NodesApi~getNodesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Node>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get nodes by parent node id
     * @param {Object} opts Optional parameters
     * @param {String} opts.parentId Parent node id
     * @param {module:api/NodesApi~getNodesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Node>}
     */
    this.getNodes = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'parentId': opts['parentId'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Node];

      return this.apiClient.callApi(
        '/nodes', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postNodes operation.
     * @callback module:api/NodesApi~postNodesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Node} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new node
     * @param {module:model/NewNode} body 
     * @param {module:api/NodesApi~postNodesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Node}
     */
    this.postNodes = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling postNodes");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Node;

      return this.apiClient.callApi(
        '/nodes', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
