/*
 * Test application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 4.3.1
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "http://localhost:5000";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.
let body, params;

export default function() {
    group("/nodes", () => {
        let url = BASE_URL + `/nodes`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "Success": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);

        // Request No. 2
        // TODO: edit the parameters of the request body.
        body = JSON.stringify({"port": 1, "name": "string", "ip": "string", "parentId": 1});
        params = {headers: {"Content-Type": "application/json"}};
        request = http.post(url, body, params);
        check(request, {
            "Created node": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
}
