/*
 * Test application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TestApplicationApi) {
      root.TestApplicationApi = {};
    }
    root.TestApplicationApi.NewNode = factory(root.TestApplicationApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The NewNode model module.
   * @module model/NewNode
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>NewNode</code>.
   * @alias module:model/NewNode
   * @class
   * @param port {Number} 
   * @param name {String} 
   * @param ip {String} 
   */
  var exports = function(port, name, ip) {
    this.port = port;
    this.name = name;
    this.ip = ip;
  };

  /**
   * Constructs a <code>NewNode</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewNode} obj Optional instance to populate.
   * @return {module:model/NewNode} The populated <code>NewNode</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('port'))
        obj.port = ApiClient.convertToType(data['port'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('ip'))
        obj.ip = ApiClient.convertToType(data['ip'], 'String');
      if (data.hasOwnProperty('parentId'))
        obj.parentId = ApiClient.convertToType(data['parentId'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} port
   */
  exports.prototype.port = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} ip
   */
  exports.prototype.ip = undefined;

  /**
   * @member {Number} parentId
   */
  exports.prototype.parentId = undefined;

  return exports;

}));
