/*
 * Test application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NewNode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NewNode'));
  } else {
    // Browser globals (root is window)
    if (!root.TestApplicationApi) {
      root.TestApplicationApi = {};
    }
    root.TestApplicationApi.Node = factory(root.TestApplicationApi.ApiClient, root.TestApplicationApi.NewNode);
  }
}(this, function(ApiClient, NewNode) {
  'use strict';

  /**
   * The Node model module.
   * @module model/Node
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Node</code>.
   * @alias module:model/Node
   * @class
   * @extends module:model/NewNode
   * @param port {Number} 
   * @param name {String} 
   * @param ip {String} 
   */
  var exports = function(port, name, ip) {
    NewNode.call(this, port, name, ip);
  };

  /**
   * Constructs a <code>Node</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Node} obj Optional instance to populate.
   * @return {module:model/Node} The populated <code>Node</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      NewNode.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }

  exports.prototype = Object.create(NewNode.prototype);
  exports.prototype.constructor = exports;
  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  return exports;

}));
