/*
 * Test application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TestApplicationApi);
  }
}(this, function(expect, TestApplicationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TestApplicationApi.NodesApi();
  });

  describe('(package)', function() {
    describe('NodesApi', function() {
      describe('getNodes', function() {
        it('should call getNodes successfully', function(done) {
          // TODO: uncomment, update parameter values for getNodes call and complete the assertions
          /*
          var opts = {};
          opts.parentId = "parentId_example";

          instance.getNodes(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(TestApplicationApi.Node);
              expect(data.port).to.be.a('number');
              expect(data.port).to.be(0);
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.ip).to.be.a('string');
              expect(data.ip).to.be("");
              expect(data.parentId).to.be.a('number');
              expect(data.parentId).to.be(0);
              expect(data.id).to.be.a('string');
              expect(data.id).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postNodes', function() {
        it('should call postNodes successfully', function(done) {
          // TODO: uncomment, update parameter values for postNodes call and complete the assertions
          /*
          var body = new TestApplicationApi.NewNode();
          body.port = 0;
          body.name = "";
          body.ip = "";
          body.parentId = 0;

          instance.postNodes(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TestApplicationApi.Node);
            expect(data.port).to.be.a('number');
            expect(data.port).to.be(0);
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.ip).to.be.a('string');
            expect(data.ip).to.be("");
            expect(data.parentId).to.be.a('number');
            expect(data.parentId).to.be(0);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
